# Generated by Django 3.1.1 on 2020-11-04 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
